# Generated by Django 5.2.7 on 2025-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=52)),
                ('last_name', models.CharField(max_length=52)),
                ('phone_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, default='icon.png', null=True, upload_to='contacts_photo/')),
            ],
        ),
    ]
